name: managed_mongo
version: 1.1.4
description: A wrapper for running a managed mongo instance from inside a Dart library or application.
author: Jim Simon <jim.j.simon@gmail.com>
homepage: https://github.com/jimsimon/managed_mongo
documentation: http://www.dartdocs.org/documentation/managed_mongo/latest/index.html#managed_mongo
dependencies:
  path: ">=1.3.2 <2.0.0"
  archive: ">=1.0.18 <2.0.0"
  dart_commons: ">=1.0.2 <2.0.0"
dev_dependencies:
  test: 'any'
  mongo_dart: 'any'